# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37ca87ed1771e5d341cf00b3f155ec175d10c6ae74b1104dc1bed72bfeda7680c8e231e8b1c3f5f768a151c746ad24189e235ae5c67392dce844161597771966

test:
  secret_key_base: a1317ed1bc2863de28c99d24bc120f4e2ce66c438e0f85f3aa82afb0bc999c4d0e62a82ec3c02743be02d31519ecf65e9ff0dfe2d032fa094bf1a06aaf0b389e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
